name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    name: test w/ Python ${{ matrix.python-version }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Nox
        run: python -m pip install --upgrade pip nox

      - name: Run tests
        run: nox --session tests-${{ matrix.python-version }}
        env:
          PYTHONDEVMODE: "1"

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cov.xml
          flags: python-${{ matrix.python-version }}
          name: python-${{ matrix.python-version }}
          fail_ci_if_error: true
          verbose: true
